/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Cartesian.Services | v1
 * OpenAPI spec version: 1.0.0
 */
import { createQuery } from "@tanstack/svelte-query";
import type {
	CreateQueryOptions,
	CreateQueryResult,
	DataTag,
	QueryClient,
	QueryFunction,
	QueryKey,
} from "@tanstack/svelte-query";

import { customInstance } from "./client";
import type { ErrorType } from "./client";
export const getExample = (signal?: AbortSignal) => {
	return customInstance<string>({ url: `/example`, method: "GET", signal });
};

export const getGetExampleQueryKey = () => {
	return [`/example`] as const;
};

export const getGetExampleQueryOptions = <
	TData = Awaited<ReturnType<typeof getExample>>,
	TError = ErrorType<unknown>,
>(options?: {
	query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetExampleQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getExample>>> = ({ signal }) =>
		getExample(signal);

	return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
		Awaited<ReturnType<typeof getExample>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetExampleQueryResult = NonNullable<Awaited<ReturnType<typeof getExample>>>;
export type GetExampleQueryError = ErrorType<unknown>;

export function createGetExample<
	TData = Awaited<ReturnType<typeof getExample>>,
	TError = ErrorType<unknown>,
>(
	options?: {
		query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getExample>>, TError, TData>>;
	},
	queryClient?: QueryClient,
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetExampleQueryOptions(options);

	const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
